theme: jekyll-theme-minimal
logo: https://www.ebi.ac.uk/training/online/sites/ebi.ac.uk.training.online/files/resize/user/61/documents/bx_terrified_fig_1_700px-696x522.jpg
title: BGGN213 Classwork

# List of links in the navigation bar
navbar-links:
  About Me: "About Me"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
