remote_theme: https://github.com/daattali/beautiful-jekyll
logo: https://www.ebi.ac.uk/training/online/sites/ebi.ac.uk.training.online/files/resize/user/61/documents/bx_terrified_fig_1_700px-696x522.jpg
title: BGGN213 Classwork

