---
title: "Clustering_and_PCA"
author: "Asha Goodman"
date: "2/6/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You can also download this file from the class website!
```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)
head(mydata)
```

Time to do our PCA
```{r}
pca <- prcomp(t(mydata), scale=TRUE)
summary(pca)
```
Cumulative is the sum of variance as you move from PC1 to PC8

See what is returned by the prcomp() function
(Summary is different in that it produces quantification/qualitative data)
```{r}
attributes(pca)
```
```{r}
plot(pca$x)
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2") 
plot(pca)
```
Variance captured per PC. Always round your significant figures.
```{r}
pca.var <- pca$sdev^2
plot(pca, col=pca.var)
pca.var.per <- round(pca.var/sum(pca.var)*100, 1) 
pca.var.per
```
```{r}
barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
```
A vector of colors for wt and ko samples.
```{r}
colvec <- as.factor( substr( colnames(mydata), 1, 2) )
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
```






